### ISSUE TITLE
One annotation error in the test dataset

### ISSUE THREAD

**Issue by jimmy-dq** [HengLan/LaSOT_Evaluation_Toolkit#10]
Hi Fan,
Thanks for your great work. I think one annotation may be wrong in the test video tiger-6, 00000118.jpg ([613,731,247,-11]). Its previous and next frames are annotated with [282,374,125,79] and [280,372,128,87], respectively.

**Comment by HengLan** [comment]
Hi Jimmy,

Thank you very much to point out this issue.I will update it in the future :) Again, thanks a lot.

Jimmy_wqq <notifications@github.com>于2020年3月24日 周二上午6:40写道：
