### ISSUE TITLE
What does the attribute bits represent in the `annos/att` directory?

### ISSUE THREAD

**Issue by fzh0917** [HengLan/LaSOT_Evaluation_Toolkit#11]
Hi, Heng Fan,
As the title says, what the attribute bits represent in the `annos/att` directory?  In other words, what's the attribute order represented by binary bits in `annos/att/*.txt`?
Besides, is there a quick way to find those videos that have common attribute(s), just like [this](http://cvlab.hanyang.ac.kr/tracker_benchmark/datasets.html).

**Comment by fzh0917** [comment]
Thank you!
Best regards! ^_^

**Comment by HengLan** [comment]
They are corresponding to 'Illumination Variation', 'Partial Occlusion', 'Deformation', 'Motion Blur', 'Camera Motion', 'Rotation', 'Background Clutter', 'Viewpoint Change', 'Scale Variation', 'Full Occlusion', 'Fast Motion', 'Out-of-View', 'Low Resolution', 'Aspect Ration Change'.

**Comment by HengLan** [comment]
To quickly search for the common attributes, you can load all attribute annotations in the matrix, and then you can easily find the videos which share the same attributes.

**Comment by fzh0917** [comment]
Yes. I have already done this. 

Thank you very much!
Best regards!
