### ISSUE TITLE
how to define whether a targer is fast or slow?

### ISSUE THREAD

**Issue by Jee-King** [HengLan/LaSOT_Evaluation_Toolkit#12]
Hi, thanks for your great datasets.

In OTB, Fast Motion is defined as the motion of the ground truth is larger than tm pixels (tm=20).
How do you define whether the target is fast or slow in LaSOT? Is it same with OTB？
or calculate it as:
![fm](https://user-images.githubusercontent.com/24266511/92983630-373b4a80-f4d7-11ea-9c17-043d1dcc45cd.png)
where pi denotes the object center location and si = sqrt(wihi) represents the object size.

Thanks！

**Comment by HengLan** [comment]
Hi, Jee-King,

Thanks for your interest. In LaSOT, the FM is defined as "The motion of the target is larger than the size (size=sqrt(w^2+h^2)) of its bounding box". Check Table 2 in the paper for definition.

Thanks.

**Comment by Jee-King** [comment]
the FM is defined as:
![1599874048(1)](https://user-images.githubusercontent.com/24266511/92984065-1fb19100-f4da-11ea-8780-757a16f8c95d.png)

i and i+1 represent two adjacent frames.
In a video sequence,  if
![vfm](https://user-images.githubusercontent.com/24266511/92984035-d6f9d800-f4d9-11ea-9f13-b096a3aae879.png)
this video is defined the FM.
 is it right?

**Comment by HengLan** [comment]
Your understanding of FM (the above equation) is correct. The P_i denotes the center point of the target in frame (i). For the bottom equation, I believe this should be right. Since a video is labeled with FM if FM happens in any one frame.

**Comment by Jee-King** [comment]
Thank you very much :rose:

**Comment by HengLan** [comment]
No problem. Glad it helps :)
