### ISSUE TITLE
Where is the tracking results?

### ISSUE THREAD

**Issue by xjtuwh** [HengLan/LaSOT_Evaluation_Toolkit#13]
The tracking result link is invalid https://cis.temple.edu/lasot/toolkit/LaSOT_Evaluation_Toolkit.zip

**Comment by xjtuwh** [comment]
http://vision.cs.stonybrook.edu/~lasot/

**Comment by HengLan** [comment]
The results of tested tracking algorithms are available in the toolkit at http://vision.cs.stonybrook.edu/~lasot/results.html. Thanks.
