### ISSUE TITLE
Is the bounding box coordinate origin 0 or 1?

### ISSUE THREAD

**Issue by kumatheworld** [HengLan/LaSOT_Evaluation_Toolkit#14]
Thanks for the great work!

I'd like to know what is the bounding box coordinate origin of this dataset. In other words, what are the smallest possible values of the left end (x0) and the top end (y0) of the bounding boxes?

As far as I checked, there was no bounding box in the 1,400 videos of the conference version that has x0=0 or y0=0. However, in about 60 videos out of the 150 of the additional journal version, there are many bounding boxes that have x0=0 or y0=0. I suspect that the coordinate origin is 1 in the conference version and 0 in the journal version. Is this intended?

**Comment by HengLan** [comment]
The smallest should be 1. Thanks.
