### ISSUE TITLE
关于网址失效问题

### ISSUE THREAD

**Issue by Scr-w** [HengLan/LaSOT_Evaluation_Toolkit#17]
您好，非常感谢您的分享，但是这个网址http://vision.cs.stonybrook.edu/~lasot/LaSOT_Evaluation_Toolkit.zip显示已经失效，请问可以再重新分享一个吗，非常感谢

**Comment by HengFan2010** [comment]
Please check it here: http://vision.cs.stonybrook.edu/~lasot/toolkit/LaSOT_Evaluation_Toolkit_V2.zip

Thanks.
