### ISSUE TITLE
Negative numbers in annotations

### ISSUE THREAD

**Issue by wdrink** [HengLan/LaSOT_Evaluation_Toolkit#19]
Hi, thanks a lot for your awesome work. I noticed that there are negative numbers in your annotations (which I think is weird), e.g.,

LaSOT/lion/lion-5/img/00000553.jpg [1, 1, -1, -1]
LaSOT/tiger/tiger-6/img/00000118.jpg [613, 731, 247, -11]

I wonder whether they are wrong annotations or have some special meanings? Looking forward to your reply

**Comment by HengFan2010** [comment]
Thanks. Please also check out the corresponding occlusion or out-of-view annotation files. The targets in these frames may be not annotated (i.e., assigned a random box) because of full occlusion or out of view. Thanks.
