### ISSUE TITLE
Can't download dataset through Google Drive

### ISSUE THREAD

**Issue by isbecky27** [HengLan/LaSOT_Evaluation_Toolkit#20]
Hi @HengLan, 

The Google Drive links are broken; I can't download LaSOT Dataset from https://bit.ly/LaSOTAll and https://bit.ly/LaSOTEach. 

Could you please update the Google Drive links? Thanks 🙏

The following picture shows the error I encountered:
![image](https://user-images.githubusercontent.com/38780162/211143451-31a3eff5-2724-44a7-9949-ddd6a5614f5e.png)

**Comment by HengFan2010** [comment]
The issue has been fixed. Please go ahead and download the dataset. Thanks.
