### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by HamadYA** [HengLan/LaSOT_Evaluation_Toolkit#22]
Hi,

The links are not working and I am unable to download the dataset.

**Comment by LitingLin** [comment]
The OneDrive links are OK. If they're not working, you can try logging into OneDrive with a Microsoft account first.

**Comment by HamadYA** [comment]
> The OneDrive links are OK. If they're not working, you can try logging into OneDrive with a Microsoft account first.

Hi, I did try that and it also failed
![image](https://github.com/HengLan/LaSOT_Evaluation_Toolkit/assets/119171585/63a7e71a-5d72-4144-b2ca-4709e46eb6bf)

**Comment by LitingLin** [comment]
https://huggingface.co/datasets/l-lt/LaSOT/tree/main

https://huggingface.co/datasets/l-lt/LaSOT-ext/tree/main

I just uploaded the datasets to Hugging Face. Due to the size limit (50GB), one file per object category.

**Comment by HamadYA** [comment]
Noted with thanks
