### ISSUE TITLE
Missing annotation file

### ISSUE THREAD

**Issue by Robotmurlock** [HengLan/LaSOT_Evaluation_Toolkit#23]
Hello,

I downloaded full dataset with extension from category OneDrive. I am not able to find sequence attribute annotations (14 attributes defined in the paper). Is there a way for obtain these annotations without downloading the full dataset?

Thanks in advance :)

**Comment by HengFan2010** [comment]
Hi 

Yes. The attribute annotations are in the evaluation toolkit which is rather smaller than the dataset. You can obtain the attribute annotations like this: 
(1) download the toolkit (like is here: http://vision.cs.stonybrook.edu/~lasot/toolkit/LaSOT_Evaluation_Toolkit_V2.zip); 
(2) Unzip the toolkit and go to the 'annos' folder; 
(3) go to the 'att' folder under the 'annos' folder, and then you can see the attribute annotation files of all the 1550 videos.

Hope it helps.

Best,

**Comment by Robotmurlock** [comment]
Hey,

I found the attribute annotations. Thanks for the help! :)
