### ISSUE TITLE
[HELP] The download links broke in the middle of downloading. 

### ISSUE THREAD

**Issue by divineSix** [HengLan/LaSOT_Evaluation_Toolkit#24]
I'm trying to download the LaSOT dataset to work on the tracking related problem, and was downloading data using the OneDrive link. However, the link broke with a `throttledRequest` error when I had finished downloading around ~75% of the data. Now, I'm unable to access the dataset to retry my download either. 

Also, all three google-drive links are broken (404 not found), so that route is also not possible. Please help.

**Comment by HengLan** [comment]
Please one drive
