### ISSUE TITLE
tracking result can not download 

### ISSUE THREAD

**Issue by zj717754140** [HengLan/LaSOT_Evaluation_Toolkit#5]
![image](https://user-images.githubusercontent.com/38878734/63237849-2be70280-c276-11e9-98ae-78d564deadfe.png)
the https can not open, seems something have  changed!

**Comment by HengLan** [comment]
Please download the tracking results and toolkit here: https://cis.temple.edu/lasot/toolkit/LaSOT_Evaluation_Toolkit.zip.

**Comment by zj717754140** [comment]
Thanks, I can download it now!




------------------ 原始邮件 ------------------
发件人: "Heng Fan"<notifications@github.com>; 
发送时间: 2019年8月19日(星期一) 晚上8:51
收件人: "HengLan/LaSOT_Evaluation_Toolkit"<LaSOT_Evaluation_Toolkit@noreply.github.com>; 
抄送: "张杰"<717754140@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [HengLan/LaSOT_Evaluation_Toolkit] tracking result can notdownload  (#5)




Please download the tracking results and toolkit here: https://cis.temple.edu/lasot/results.html.
