### ISSUE TITLE
Mismatch in #images vs. annotations for certain sequences

### ISSUE THREAD

**Issue by alrikai** [HengLan/LaSOT_Evaluation_Toolkit#6]
Hello, 

I noticed that sequences `airplane-14`, `airplane-15`, and `bus-4` seem to have an off-by-one mismatch in the number of images compared to the number of annotations (in `groundtruth.txt`, `full_occlusion.txt`, and `out_of_view.txt`). 
More specifically, 
- `airplane-14` has 2822 images; `groundtruth.txt` has 2821 lines. 
- `airplane-15` has 4501 images; `groundtruth.txt` has 4500 lines. 
- `bus-4` has 3972 images; `groundtruth.txt` has 3971 lines. 

and the corresponding `full_occlusion.txt` and `out_of_view.txt` files have the same number of comma separated elements as the `groundtruth.txt` file for the above sequences. 

I downloaded the dataset a few weeks ago (from the google drive link) at https://cis.temple.edu/lasot/download.html.

Am I the only one with this issue? Or is this issue already fixed in a more recent version of the dataset and I need to re-download it? (I would verify this myself, but it's a rather large download). 

Thanks!

**Comment by HengLan** [comment]
Hi, 

Sorry for the late reply. I was checking the sequences you mentioned and find that airplane-14 had 2821 images, airplane-15 has 4500 images, and bus-4 has 3791 images. How did you get the number of images for these three videos?

**Comment by HengLan** [comment]
You can use the hashing code for verifying. I checked again and the data is ok in the sever.

**Comment by alrikai** [comment]
Thanks for the verification, I had initially loaded the data in python and noticed the mismatch, then checked via the command line in the unzipped data set, i.e. 
```
$ ls airplane/airplane-15/img/ | wc -l
4501

$ cat airplane/airplane-15/groundtruth.txt | wc -l
4500
```
I'll check the md5 hash, thanks!

**Comment by alrikai** [comment]
Alright, so this is pretty weird -- I re-downloaded dataset and validated the md5 hash to match (2f9fb392c6e2ce0192bba0d531703e2d). Now there is still a mismatch, but with different numbers. i.e. 

- `airplane-14` has 2822 images and 2821 annotations
- `airplane-15` has 4501 images and 4500 annotations
- `bus-4` has  3972 images and 3971 annotations

![image](https://user-images.githubusercontent.com/2113058/64507537-e1164480-d28f-11e9-97d6-a70e5cfdcb85.png)

**Comment by alrikai** [comment]
The hashes did not match, and after finally managing to re-download the dataset, it all seems good. Thanks for the help
