### ISSUE TITLE
problem about downloading test dataset 

### ISSUE THREAD

**Issue by tiankongzhang** [HengLan/LaSOT_Evaluation_Toolkit#8]
I have a trouble about download lasot test dataset. When downloading the this test dataset, it happen a error,"抱歉，您目前无法查看或下载此文件。最近查看或下载此文件的用户过多。请稍后再尝试访问此文件。如果您尝试访问的文件特别大或由很多人一起共享，则可能需要长达 24 小时才能查看或下载该文件。如果 24 小时后您仍然无法访问文件，请与您的域管理员联系。". But i desperately need your test dataset for testing our model, So I want to consult you about how to download last test dataset. Thank you very much for your response.

**Comment by HengLan** [comment]
Did you download the test set from the Temple website? I tried, and can
download it. Could you have another try and tell me how it is going?

**Comment by HengLan** [comment]
By the way, downloading the dataset needs access to Google. Can you visit
Google?
