### ISSUE TITLE
Can't download dataset with Google Drive

### ISSUE THREAD

**Issue by SilvioGiancola** [HengLan/LaSOT_Evaluation_Toolkit#9]
Hi @HengLan,

It looks like your Google Drive link is broken, I can't download your LaSOT on https://bit.ly/LaSOTAll. Can you please update your Google Drive link? 

Thanks

**Comment by HengLan** [comment]
Hi, Silvio,

I tried this link, and it is still validated for downloading. Could you
show me a picture of the error you encountered?
